#CC     = gcc -Wall
CC      = gcc
#CC     = cc 
INC     = -I./../include # -I./include -I/usr/include
CFLAGS = -O3 -march=nocona ${INC}
#CFLAGS = -g -Wall ${INC}

FORECASTLIB  = forecastLib.a
LIBOBJS = forecastOptUtils.o gridDateTime.o ioUtils.o sunae.o timeUtils.o errorAnalysis.o

.c.o:
	${CC} ${CFLAGS} -c $*.c

${FORECASTLIB}: ${LIBOBJS}
	ar rv ${FORECASTLIB} ${LIBOBJS}

clean:
	rm -f ${LIBOBJS} ${FORECASTLIB}

#install:
#       make ${LIBSRC}
#       cp -p ${LIBSRC} ${LLIBDIR}

