#CC     = gcc -Wall
CC      = gcc
#CC     = cc 
INC     = -I./../include # -I./include -I/usr/include 
CFLAGS = -O3 -march=nocona ${INC} 
#CFLAGS = -g -Wall -DNSUNAEDUMP ${INC}
#CFLAGS = -g -Wall ${INC}

LIBDIR  = ./satLib
SATLIB  = satLib.a
LIBOBJS = sunae.o ioUtils.o timeUtils.o gridDateTime.o 

.c.o:
	${CC} ${CFLAGS} -c $*.c

${SATLIB}: ${LIBOBJS}
	ar rv ${SATLIB} ${LIBOBJS}

clean:
	rm -f ${LIBOBJS} ${SATLIB}

#install:
#       make ${LIBSRC}
#       cp -p ${LIBSRC} ${LLIBDIR}

